### PR TITLE
Changed API to use JSON body requests instead of URL args

### LINKED ISSUE #23: Change all API to json
API should receive JSON on every POST, not ugly query params.

### PR DESCRIPTION
**Pull request by rdelfin**
Resolves #23

### CODE REVIEW

**Comment by franspaco** [comment]
I'm just gonna say: https://github.com/bunchiestudios/schedulr/blob/master/app/helpers/req_helper.py

**Comment by rdelfin** [comment]
@franspaco yeah, I know, I modified that function. Didn't quite work like the rest of the API (how it does errors), and made it into a decorator

**Comment by franspaco** [comment]
you outright deleted all my helper, savage... also, the old function serves the secondary purpose of ensuring specific keys are provided in the json, thing you're doing manually now

**Comment by rdelfin** [comment]
_AH_ let me add that back in

**Comment by franspaco** [comment]
update pending

**Comment by rdelfin** [comment]
Wrapped up. Should be g2g. Just need to actually test changes

**Comment by rdelfin** [comment]
Oh fuck there were a couple commits missing

**Pull request merged**
