### PR TITLE
Formatted code with black 

### PR DESCRIPTION
**Pull request by rdelfin**
Formatted code according to https://github.com/ambv/black

### CODE REVIEW

**Comment by franspaco** [comment]
i feel offended by double quotes

**Comment by rdelfin** [comment]
I won't lie, I kind of do as well, but it's good to have an opinionated formatter that keeps code... Consistent

**Comment by franspaco** [comment]
what if we run this... _after_ we have finished adding code like crazy... otherwise we're gonna be doing this quite often

**Comment by rdelfin** [comment]
I was thinking of adding an automated check here, but that's fair. I'll close

**Pull request closed without merging**
